sbatch make_file/nskt_16k_WDSR_8.sbatch
sbatch make_file/nskt_16k_WDSR_16.sbatch
sbatch make_file/nskt_32k_WDSR_8.sbatch
sbatch make_file/nskt_32k_WDSR_16.sbatch
sbatch make_file/nskt_16k_sim_WDSR_4.sbatch
sbatch make_file/nskt_32k_sim_WDSR_4.sbatch
